# Generated by Django 4.1.4 on 2022-12-16 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_noticias_alter_comentarios_noticia_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('cuerpo_evento', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('hora_comienzo', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
                ('modalidad', models.BooleanField(default=True)),
                ('lugar', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('publicado', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
