# Generated by Django 4.1.4 on 2022-12-23 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('img', models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/noticias')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('publicado', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='categorias',
        ),
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.AddField(
            model_name='noticia',
            name='categorias',
            field=models.ManyToManyField(related_name='noticias', to='blog.categoria'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.noticia'),
        ),
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
